import { collection, onSnapshot, orderBy, query } from "firebase/firestore";
import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";
import Message from "../components/message";
import { db } from "../utils/firebase";
import { AiOutlineComment } from "react-icons/ai";

export default function Home() {
  //Create state for all the posts
  const [allPosts, setAllPosts] = useState([]);

  const getPosts = async () => {
    const collectionRef = collection(db, "posts");
    const q = query(collectionRef, orderBy("timestamp", "desc"));
    const unsubscribe = onSnapshot(q, (snapshot) => {
      setAllPosts(snapshot.docs.map((doc) => ({ ...doc.data(), id: doc.id })));
    });
    return unsubscribe;
  };

  useEffect(() => {
    getPosts();
  }, []);

  return (
    <div>
      <Head>
        <title>Comment Ideas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="my-12 text-lg font-medium">
        <h2>See other people thoughts 😎</h2>
        {allPosts.map((post) => {
          return (
            <Message key={post.id} {...post}>
              <Link href={{ pathname: `${post.id}`, query: { ...post } }}>
                <button className="flex gap-2 float-right mr-6 items-center text-md">
                  {post.comments?.length > 0 ? post.comments?.length : 0}
                  <AiOutlineComment />
                </button>
              </Link>
            </Message>
          );
        })}
      </div>
    </div>
  );
}
